mcux: Update hal_nxp.cmake to use new zephyr_code_relocate API
zephyrproject-rtos/hal_nxp pull request #195
Opened 2022-10-04 23:44 UTC by danieldegrasse

Update hal_nxp.cmake to use new zephyr_code_relocate API to relocate flexSPI flash driver to ITCM

Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>

2022-10-10 18:26 UTC, danieldegrasse commented
We should hold on merging this until the associated Zephyr PR (50791) is unblocked, since this change would be breaking if it went in too early.

2022-10-10 19:09 UTC, dleach02 requested changes
We will wait on Zephyr 50791

2023-01-12 13:55 UTC, tejlmand approved these changes

2023-01-12 13:57 UTC, carlescufi approved these changes
https://github.com/zephyrproject-rtos/zephyr/pull/50791 is approved

2023-01-17 10:23 UTC, merged