Rename S32 to NXP S32
zephyrproject-rtos/hal_nxp pull request #216
Opened 2022-12-27 14:53 UTC by manuargue

Following updates previously done for other drivers and as requested by reviewers (e.g. https://github.com/zephyrproject-rtos/zephyr/pull/51451#issuecomment-1294384579), rename all occurrences of S32 to NXP S32 to avoid ambiguity.

2022-12-30 08:42 UTC, henrikbrixandersen requested changes
LGTM once the HAL change is merged.

2022-12-30 08:44 UTC, henrikbrixandersen approved these changes

2023-01-03 04:41 UTC, manuargue commented
@dleach02 @danieldegrasse could you pls have a look at this patch? thanks

2023-01-03 16:51 UTC, dleach02 approved these changes
@manuargue, we need to coordinate this merge as there are a number of S32 changes. 

ping me so we can do this.

2023-01-04 14:13 UTC, merged