Add support for newly introduced CCM Rev3 on i.MX93
zephyrproject-rtos/hal_nxp pull request #247
Opened 2023-06-28 08:46 UTC by LaurentiuM1234

This series of changes will make sure that the CCM Rev3 driver from Zephyr is supported on i.MX93

2023-07-06 13:08 UTC, LaurentiuM1234 commented
@dleach02 @mmahadevan108 @danieldegrasse pls review.

2023-07-11 16:05 UTC, mmahadevan108 commented on mcux/mcux-sdk/devices/MIMX9352/MIMX9352_ca55_features.h
> +
This should be passed in from the Zephyr side during compile.

2023-07-11 16:06 UTC, mmahadevan108 commented on mcux/mcux-sdk/devices/MIMX9352/drivers/fsl_clock.h
> +
This should be a PR to the SDK code. We do not want to maintain changes to SDK code in the Zephyr HAL repo.

2023-07-11 16:07 UTC, mmahadevan108 commented
@LaurentiuM1234, please work with the SDK team to update the SDK `fsl_clock` driver. We cannot maintain these changes inside the Zephyr HAL.

2023-07-11 16:09 UTC, mmahadevan108 requested changes
I feel most of the changes can be addressed by 
1. Working with the SDK team to update the clock driver
2. Adding changes to Zephyr to pass in the compile time defines. You can refer to the the MXRT code to see how this has been done.

2023-07-13 13:41 UTC, LaurentiuM1234 commented
> @LaurentiuM1234, please work with the SDK team to update the SDK `fsl_clock` driver. We cannot maintain these changes inside the Zephyr HAL.

These changes are based on the MIMX9352 support introduced by @JiafeiPan. This support was only merged in the NXP HAL and not the mcux_sdk repo. Without the support added to mcux_sdk repo I can't add the changes from this PR.

@JiafeiPan can you please add a PR to the mcux-sdk in which you add the support for MIMX9352?

2023-09-12 07:52 UTC, LaurentiuM1234 commented
@mmahadevan108 mcux-sdk PR https://github.com/nxp-mcuxpresso/mcux-sdk/pull/133 has been merged. Could we also merge this please?

2023-09-13 22:18 UTC, mmahadevan108 commented
The Update to SDK 2.14 should pull this in. PR to update to 2.14: https://github.com/zephyrproject-rtos/hal_nxp/pull/270

2023-09-13 22:21 UTC, mmahadevan108 commented
Please close this PR is it is addressed by the update to 2.14.

2023-09-14 07:23 UTC, closed without merging