drivers: csi: Rework to fix the low framerate issue
zephyrproject-rtos/hal_nxp pull request #372
Opened 2024-04-12 16:08 UTC by ngphibang

Currently, the camera framerate is divided by two. This is because the driver only puts the full buffer to the queue and calls the callback at half of the interrupt rate (when there are at least 2 active framebuffers).

This issue is not really visible when using more than two buffers and the application does not hold the full buffer for too long before submitting it again to the empty buffers queue. But if we use only two buffers, the framerate is clearly reduced (by a factor of two).

Especially, when CSI_TransferGetFullBuffer() get called inside the callback function (as in Zephyr RTOS), framerate is always reduced by a factor of two despite of the number of buffers used.

Rework the driver to fix these issues as well as to clean up the logics.

2024-04-29 19:40 UTC, dleach02 commented
@ngphibang, I think we need to wait on your SDK PR to resolve its discussions before merging this one.

2024-04-29 19:41 UTC, dleach02 requested changes
Wait on SDK PR https://github.com/nxp-mcuxpresso/mcux-sdk/pull/188 to resolve discussions.

2024-05-06 13:23 UTC, ngphibang commented
@dleach02 @mmahadevan108 : I had discussions with Jason (the PR is technically correct. The discussions are just about keeping or not the exact original behavior of calling the callback in case of someone has been familiar with the old behavior, if any) and we come to an agreement.
The PR is now merged into MCUX SDK. Could you help to merge this into the hal_nxp ?
Thanks !

2024-05-10 19:34 UTC, dleach02 approved these changes

2024-05-10 19:35 UTC, dleach02 commented
@mmahadevan108

2024-05-14 22:09 UTC, ngphibang commented
Just resolved the merge conflict of the patch number in README as this is on the point to be merged

2024-05-15 18:17 UTC, decsny approved these changes

2024-05-15 19:55 UTC, merged