s32: convert SIUL2 driver to native driver
zephyrproject-rtos/hal_nxp pull request #411
Opened 2024-07-18 11:03 UTC by manuargue

Convert SIUL2 pin control, GPIO and external interrupt controller to native drivers and remove sources no longer needed.

2024-07-19 02:06 UTC, bperseghetti approved these changes

2024-07-19 02:24 UTC, Dat-NguyenDuy requested changes
Pls re-generate the new pinmux macros in dts/nxp/s32/*. Previously, we use the RTD driver, it handles the imcr index arbitrarily (i.e on s32z, with siul2_3: imcr index= imcr index in iomux sheet, whether for the rest of instance, imcr index = imcr index in iomux sheet - 512).

With this native approach, i believe this can be done consistently for all siul2 instances

2024-07-19 11:40 UTC, PetervdPerk-NXP approved these changes

2024-07-19 17:12 UTC, bperseghetti approved these changes

2024-07-19 20:25 UTC, dleach02 approved these changes

2024-07-22 03:03 UTC, Dat-NguyenDuy commented
> Pls re-generate the new pinmux macros in dts/nxp/s32/*. Previously, we use the RTD driver, it handles the imcr index arbitrarily (i.e on s32z, with siul2_3: imcr index= imcr index in iomux sheet, whether for the rest of instance, imcr index = imcr index in iomux sheet - 512).
> 
> With this native approach, i believe this can be done consistently for all siul2 instances

Thanks for the update, but i have just found one more issue that is on such platform like the s32z, imcr and mscr index for pin may not belong to the same siul2 instance. For e.g PA5_CAN_0_RX: mscr_5-siul2_0; imcr_0 - siul2_3. So i think you might need to extend the macro in https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/dt-bindings/pinctrl/nxp-s32-pinctrl.h#L72 to separate siul2 index to siul2_mscr and siul2_imcr? Your implementation for the pinctrl driver need to be updated also

2024-07-22 03:10 UTC, manuargue commented
> Thanks for the update, but i have just found one more issue that is on such platform like the s32z, imcr and mscr index for pin may not belong to the same siul2 instance. For e.g PA5_CAN_0_RX: mscr_5-siul2_0; imcr_0 - siul2_3. So i think you might need to extend the macro in https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/dt-bindings/pinctrl/nxp-s32-pinctrl.h#L72 to separate siul2 index to siul2_mscr and siul2_imcr? Your implementation for the pinctrl driver need to be updated also

please log an issue and let's address that once this pr is merged, because that's a pre-existing issue not related to this pr

2024-07-22 05:29 UTC, Dat-NguyenDuy approved these changes

2024-07-29 10:17 UTC, merged