add possibility for XBARB
zephyrproject-rtos/hal_nxp pull request #442
Opened 2024-09-26 08:12 UTC by lam-borg

We are using the xbarb and it would be nice to have this possibility in the upstream repo aswell.
Thanks for considering

2024-10-09 21:06 UTC, EmilioCBen approved these changes

2024-10-10 13:30 UTC, lam-borg commented
Thanks for reviewing and approval!

Now we just need one more with the right to merge it...

Literally one click away!

2024-10-15 20:24 UTC, dleach02 requested changes
@lam-borg, please ensure your commit messages are signed. While this is the NXP HAL, we follow the Zephyr contribution guidelines.

Also, you have two commits in this PR for a oneline change so clean up the commits.

2024-10-16 09:00 UTC, lam-borg commented
@dleach02 Thanks for your input; I fixed it accordingly.
- cleaned up
- signed off
- commit comment according guidelines

2024-10-22 01:16 UTC, dleach02 commented
@lam-borg just realized that we need a Zephyr side manifest PR to point to this

2024-10-22 12:13 UTC, lam-borg commented
I made a pull request in zephyr as well: https://github.com/zephyrproject-rtos/zephyr/pull/80225

Anything that i need to add there or here?

2024-10-23 14:24 UTC, danieldegrasse commented
Yes, you need to update the west manifest in that PR to point to this HAL PR. Some documentation is available here: https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules

2024-10-24 18:12 UTC, mmahadevan108 approved these changes

2024-10-30 12:05 UTC, lam-borg commented
Somehow, my zephyr PR is waiting on this PR. Did I miss anything? What can I do to get it through?

2024-10-30 14:14 UTC, danieldegrasse approved these changes

2024-10-30 14:16 UTC, danieldegrasse commented
> Somehow, my zephyr PR is waiting on this PR. Did I miss anything? What can I do to get it through?

So the process we follow for HAL PRs is the following:
- wait until Zephyr PR is ready to merge (IE 2 project collaborators have approved it, and all CI is passing except do not merge check)
- Merge HAL side PR
- Contributor will update the Zephyr side PR to now use the latest SHA of the NXP HAL
- CI runs again, reviewers reapprove, and the Zephyr side PR merges

Since we are now in the 4.0 feature freeze this process will be delayed until after the 4.0 release, but those are the steps we will follow to get this merged.

2024-10-30 14:37 UTC, lam-borg commented
@danieldegrasse ok, thanks for approval and the clarification!

2024-12-03 14:57 UTC, bia-bonobo commented
@dleach02 I think your requested changes have been completed. Can you have a look at this again?

2024-12-12 20:45 UTC, dleach02 commented
yes, we need to now coordinate the merge with you zephyr side PR

2024-12-12 20:46 UTC, dleach02 approved these changes

2025-01-18 17:46 UTC, merged