mcux: add support for imxrt1176 rtwdog
zephyrproject-rtos/hal_nxp pull request #449
Opened 2024-10-11 11:41 UTC by danielb-tkjcy3rq

This is in preparation for adding a Zephyr watchdog driver for wdog3 and wdog4 found on the imxrt1170 MCUs.

2024-10-15 20:15 UTC, danieldegrasse commented on mcux/hal_nxp.cmake
> +include_driver_ifdef(CONFIG_WDT_MCUX_IMX_RTWDOG	rtwdog		driver_rtwdog)
Can you align indentation here?

2024-10-15 20:19 UTC, danieldegrasse commented
> This is in preparation for adding a Zephyr watchdog driver for wdog3 and wdog4 found on the imxrt1170 MCUs.

Typically the sequence we follow is to submit the Zephyr side PR referencing the HAL module update- then once the Zephyr side PR is passing CI and has been reviewed (IE nearly ready to merge), we update the HAL module, and then the contributor will perform one final update to the Zephyr side to pull in the latest revision of the HAL main branch. At that point the Zephyr side PR can merge.

For this case, I'd submit the RTWDOG driver to Zephyr, and reference this PR for the NXP HAL module revision in that PR.

For more details, take a look at the module update procedure: https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules.

This PR is in progress, and has an example of the update process: https://github.com/zephyrproject-rtos/zephyr/pull/79376/files#diff-d7f4082837dc3cb270fcf1abd68188216fdadee294e01611b8ca59ddea7fdbb3

2024-10-22 01:19 UTC, dleach02 commented
@danielb-tkjcy3rq we need a Zephyr side manifest PR

2025-01-24 16:51 UTC, mmahadevan108 commented
@danielb-tkjcy3rq , any update on the Zephyr side PR for this change to the HAL.

2025-01-28 11:56 UTC, danielb-tkjcy3rq commented
> @danielb-tkjcy3rq , any update on the Zephyr side PR for this change to the HAL.

Sorry not yet. Things have been and are a bit manic at work. I will try to get back to this next week.

2025-03-28 16:54 UTC, dleach02 requested changes
@danielb-tkjcy3rq we recently updated the HAL to used SDK-NG. We also moved the glue code to Zephyr repo under modules\hal_nxp. I suspect this PR is no longer needed in the HAL.

2025-04-21 16:56 UTC, dleach02 commented
@danielb-tkjcy3rq do you intend on returning to this PR?

2025-05-30 20:50 UTC, decsny commented
this cmake should be added in zephyr repo, not here

2025-05-30 20:50 UTC, closed without merging