drivers: sai: the 1st frame synchronization signal lost in slave side
zephyrproject-rtos/hal_nxp pull request #490
Opened 2024-12-17 22:56 UTC by Raymond0225

According the RM document, RT1170 58.3.3 (should be same for other MCU which has a similiar SAI IP):
"A valid frame sync is also ignored (slave mode) or not generated (master mode) for the first four bit clock cycles after enabling the transmitter or receiver."
but in fact, we found master side send out a valid frame sync at the 3rd bit clock cycles which cause this frame sync is ignored by the slave side and frame data lost.
To workaround this issue, bit clock is enabled before TE/RE.

2024-12-17 23:01 UTC, decsny commented
Has this change been submitted to the SDK ? All PRs to this repo that change SDK code need to be upstreamed to the SDK so that we don't need to keep repatching after updating to new SDKs (this repo is a "public downstream" of the "internal upstream" SDK)

2024-12-17 23:18 UTC, Raymond0225 commented
> Has this change been submitted to the SDK ? All PRs to this repo that change SDK code need to be upstreamed to the SDK so that we don't need to keep repatching after updating to new SDKs (this repo is a "public downstream" of the "internal upstream" SDK)

I am submitting to internal upstream at the same time.

2025-01-08 17:18 UTC, Raymond0225 commented
This patch has been submitted to internal SDK repo and got merged.

2025-01-10 17:47 UTC, decsny approved these changes

2025-01-10 19:24 UTC, EmilioCBen approved these changes

2025-01-10 22:15 UTC, dleach02 approved these changes

2025-01-10 22:16 UTC, dleach02 commented
there needs to be a Zephyr side PR to update the manifest. I see that it has been mentioned though in a couple.

2025-01-10 22:35 UTC, dleach02 requested changes
Add Zephyr side manifest update

2025-01-13 19:39 UTC, Raymond0225 commented
> Add Zephyr side manifest update

it is here:  https://github.com/zephyrproject-rtos/zephyr/pull/83718

2025-01-17 04:29 UTC, dleach02 approved these changes

2025-01-21 20:53 UTC, Raymond0225 commented
do you think I should update the readme file and include the description of this patch? 
https://github.com/zephyrproject-rtos/hal_nxp/blob/master/mcux/README#L127

2025-01-21 22:10 UTC, decsny commented
> do you think I should update the readme file and include the description of this patch? https://github.com/zephyrproject-rtos/hal_nxp/blob/master/mcux/README#L127

if it was merged to sdk upstream then not needed

2025-01-24 19:27 UTC, merged