mcux: drivers: imx: add flexcan support
zephyrproject-rtos/hal_nxp pull request #55
Opened 2020-08-26 21:26 UTC by rtalbott

Add support for flexcan on RT series processors.

2020-08-26 21:29 UTC, henrikbrixandersen requested changes
Please get rid of the merge commit. Otherwise looks good.

2020-10-10 19:33 UTC, henrikbrixandersen requested changes

2020-10-10 19:33 UTC, henrikbrixandersen commented on mcux/drivers/imx/CMakeLists.txt
> +
You need to get rid of the empty, trailing line - and add a body + signed-off line to the commit log message.

2020-10-10 20:36 UTC, henrikbrixandersen approved these changes

2020-10-12 13:38 UTC, MaureenHelm approved these changes

2020-10-12 13:38 UTC, merged