MXRT600: Add SDK I2S drivers
zephyrproject-rtos/hal_nxp pull request #77
Opened 2021-02-08 15:08 UTC by mmahadevan108

Builds the i.MX RT600 I2S driver when the corresponding i2sx shim driver is enabled.

I2S Support is added as part of PR https://github.com/zephyrproject-rtos/zephyr/pull/32054

2021-02-08 15:29 UTC, galak approved these changes

2021-02-19 17:10 UTC, MaureenHelm requested changes
Can you add this to `mcux/drivers/lpc/CMakeLists.txt` too?

2021-02-19 21:16 UTC, mmahadevan108 commented
> Can you add this to `mcux/drivers/lpc/CMakeLists.txt` too?
Done

2021-02-19 21:30 UTC, MaureenHelm approved these changes

2021-02-19 21:30 UTC, merged