mcux: Relocate FlexSPI driver with XIP
zephyrproject-rtos/hal_nxp pull request #82
Opened 2021-03-26 10:11 UTC by pdgendt

Relocates the i.MX RT FlexSPI driver to the configured memory target if required.

This commit is needed for https://github.com/zephyrproject-rtos/zephyr/pull/33701

2021-03-30 21:48 UTC, MaureenHelm requested changes
Will you please make the same change to `mcux/drivers/imxrt6xx/CMakeLists.txt`

2021-04-01 22:12 UTC, mmahadevan108 approved these changes
Thank you. It would be great if you could add something similar for RT600

2021-04-02 06:55 UTC, pdgendt commented
I'll edit the RT600, but I don't have hardware to test this..

Also can the [HyperRAM driver PR](https://github.com/zephyrproject-rtos/zephyr/pull/33602) get merged, so I can resolve any conflicts and test both changes?

2021-04-14 21:54 UTC, MaureenHelm approved these changes

2021-04-14 21:57 UTC, merged