driver: lpadc: add support for the lpadc driver
zephyrproject-rtos/hal_nxp pull request #92
Opened 2021-07-02 15:27 UTC by CristXu

add SDK support for rt1170's lpadc driver

Signed-off-by: Crist Xu <crist.xu@nxp.com>

2021-07-09 15:25 UTC, dleach02 approved these changes

2021-07-12 12:45 UTC, galak approved these changes

2021-07-14 21:26 UTC, MaureenHelm requested changes

2021-07-14 21:26 UTC, MaureenHelm commented on mcux/drivers/imx/CMakeLists.txt
> +zephyr_library_sources_ifdef(CONFIG_ADC_MCUX_LPADC	fsl_lpadc.c)
Please move this up to preserve alpha order by Kconfig symbol

2021-07-20 14:16 UTC, MaureenHelm approved these changes

2021-07-20 14:16 UTC, merged